# Generated by Django 4.2 on 2025-07-10 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('analysis_type', models.CharField(choices=[('enrichment', '富集分析'), ('neural', '神经网络分析'), ('coexpression', '激素-基因共表达网络分析'), ('evolution', '进化保守性分析'), ('timeseries', '动态时序建模'), ('phenotype', '表型关联富集分析')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '进行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('input_file', models.FileField(upload_to='uploads/')),
                ('progress', models.IntegerField(default=0)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hormone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receptor_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='受体类型')),
                ('receptor_name', models.CharField(max_length=255, verbose_name='受体名称')),
                ('gene_family', models.CharField(blank=True, max_length=255, null=True, verbose_name='基因家族')),
                ('gene_name_symbol', models.CharField(blank=True, max_length=255, null=True, verbose_name='基因名称/符号')),
                ('ligand', models.CharField(blank=True, max_length=255, null=True, verbose_name='配体')),
                ('ligand_type_comments', models.TextField(blank=True, null=True, verbose_name='配体类型/注释')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '激素受体数据',
                'verbose_name_plural': '激素受体数据',
                'db_table': 'hormone_receptors_table',
            },
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('authors', models.CharField(max_length=255, verbose_name='作者')),
                ('year', models.IntegerField(verbose_name='发表年份')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('file', models.FileField(upload_to='literature_files/', verbose_name='文献文件')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('lit_type', models.CharField(choices=[('ARTICLE', '期刊论文'), ('THESIS', '学位论文'), ('REPORT', '研究报告'), ('OTHER', '其他')], default='ARTICLE', max_length=50, verbose_name='文献类型')),
            ],
            options={
                'verbose_name': '文献',
                'verbose_name_plural': '文献',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='机构')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='职位')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.TextField(max_length=10000, verbose_name='分析序列')),
                ('results', models.JSONField(verbose_name='分析结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '分析历史',
                'verbose_name_plural': '分析历史',
                'ordering': ['-created_at'],
            },
        ),
    ]
