# Generated by Django 4.2 on 2025-07-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hormone_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HormoneRawData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('hormone', models.TextField(verbose_name='激素名称/结构')),
                ('pmid', models.CharField(blank=True, max_length=255, null=True, verbose_name='PMID')),
                ('receptors_in_article', models.CharField(blank=True, max_length=255, null=True, verbose_name='文章中的受体')),
                ('gene_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='基因名称')),
                ('gene_sequence', models.TextField(blank=True, null=True, verbose_name='基因序列')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '激素原始数据',
                'verbose_name_plural': '激素原始数据',
                'db_table': 'hormone_raw_data',
            },
        ),
    ]
