# Generated by Django 4.2 on 2025-07-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hormone_app', '0002_hormonerawdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hormonerawdata',
            name='receptors_in_article',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='文章中的受体'),
        ),
    ]
