# Generated by Django 4.2 on 2025-08-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hormone_app', '0003_alter_hormonerawdata_receptors_in_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='HormoneReceptorFull',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hormone_uniprot_id', models.CharField(blank=True, max_length=50, null=True)),
                ('hormone_name', models.CharField(max_length=255)),
                ('hormone_species_name', models.CharField(max_length=255)),
                ('hormone_coding_genes', models.CharField(blank=True, max_length=255, null=True)),
                ('hormone_coding_genes_sequence', models.TextField(blank=True, null=True)),
                ('receptor_uniprot_id', models.CharField(blank=True, max_length=50, null=True)),
                ('receptor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('receptor_species_name', models.CharField(blank=True, max_length=255, null=True)),
                ('receptor_coding_genes', models.CharField(blank=True, max_length=255, null=True)),
                ('receptor_coding_genes_sequence', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '激素-受体完整信息',
                'verbose_name_plural': '激素-受体完整信息',
                'db_table': 'hormone_receptor_full',
            },
        ),
        migrations.CreateModel(
            name='HormoneReceptorInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pubchem_id', models.IntegerField()),
                ('hormone_name', models.CharField(max_length=255)),
                ('receptor_uniprot_id', models.CharField(max_length=50)),
                ('receptor_coding_genes', models.CharField(max_length=255)),
                ('receptor_name', models.CharField(max_length=255)),
                ('receptor_species_name', models.CharField(max_length=255)),
                ('receptor_coding_genes_sequence', models.TextField()),
            ],
            options={
                'verbose_name': '激素受体信息',
                'verbose_name_plural': '激素受体信息',
                'db_table': 'hormone_receptor_info',
            },
        ),
        migrations.CreateModel(
            name='HormoneRelatedGene',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hormone_name', models.CharField(max_length=255)),
                ('related_genes', models.CharField(max_length=255)),
                ('pmid', models.IntegerField()),
                ('gene_sequence', models.TextField()),
            ],
            options={
                'verbose_name': '激素相关基因',
                'verbose_name_plural': '激素相关基因',
                'db_table': 'hormone_related_genes',
            },
        ),
    ]
