# Generated by Django 4.2 on 2025-09-11 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hormone_app', '0004_hormonereceptorfull_hormonereceptorinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScAnalysisTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(default='未命名分析', max_length=200)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('qc_params', models.JSONField(blank=True, default=dict)),
                ('normalization_params', models.JSONField(blank=True, default=dict)),
                ('clustering_params', models.JSONField(blank=True, default=dict)),
                ('annotation_params', models.JSONField(blank=True, default=dict)),
                ('de_params', models.JSONField(blank=True, default=dict)),
                ('enrichment_params', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScUploadedFile',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('sc-data', '单细胞表达数据'), ('metadata', '细胞元数据'), ('gene-list', '基因列表'), ('sample-info', '样本信息'), ('marker-genes', '标记基因'), ('custom-genesets', '自定义基因集')], max_length=20)),
                ('file', models.FileField(upload_to='sc_uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='文件大小(字节)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='hormone_app.scanalysistask')),
            ],
        ),
        migrations.CreateModel(
            name='ScAnalysisResult',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_type', models.CharField(choices=[('anndata', '处理后的AnnData文件'), ('de-genes', '差异表达基因'), ('cell-annotations', '细胞注释'), ('enrichment', '富集分析结果'), ('visualizations', '可视化图表'), ('report', '分析报告')], max_length=20)),
                ('file', models.FileField(upload_to='sc_results/')),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='hormone_app.scanalysistask')),
            ],
        ),
    ]
