# Generated by Django 4.2 on 2025-10-12 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hormone_app', '0005_scanalysistask_scuploadedfile_scanalysisresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_name', models.CharField(default='Untitled Analysis', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneAnalysisTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(default='未命名基因分析', max_length=200)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('data_params', models.JSONField(blank=True, default=dict)),
                ('normalization_params', models.JSONField(blank=True, default=dict)),
                ('de_params', models.JSONField(blank=True, default=dict)),
                ('visualization_params', models.JSONField(blank=True, default=dict)),
                ('pathway_params', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('methyl_data', 'Methylation Data'), ('metadata', 'Sample Metadata'), ('regions', 'Genomic Regions'), ('expression', 'Expression Data'), ('custom_genesets', 'Custom Gene Sets')], max_length=20)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='hormone_app.analysisjob')),
            ],
        ),
        migrations.CreateModel(
            name='GeneUploadedFile',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('expression-data', '表达数据'), ('sample-info', '样本信息'), ('gene-annotations', '基因注释'), ('pathway-data', '通路数据'), ('contrast-definitions', '对比定义')], max_length=20)),
                ('file', models.FileField(upload_to='gene_uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='文件大小(字节)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='hormone_app.geneanalysistask')),
            ],
        ),
        migrations.CreateModel(
            name='GeneAnalysisResult',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_type', models.CharField(choices=[('normalized-data', '标准化数据'), ('de-results', '差异表达结果'), ('volcano-plot', '火山图'), ('heatmap', '热图'), ('pathway-analysis', '通路分析结果'), ('report', '分析报告')], max_length=30)),
                ('file', models.FileField(upload_to='gene_results/')),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='hormone_app.geneanalysistask')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('dmp', 'Differentially Methylated Positions'), ('dmr', 'Differentially Methylated Regions'), ('enrichment', 'Enrichment Results'), ('methyl_values', 'Methylation Values'), ('visualization', 'Visualization'), ('summary', 'Summary Statistics')], max_length=20)),
                ('file', models.FileField(upload_to='results/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='hormone_app.analysisjob')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('quality_control', 'Quality Control'), ('preprocessing', 'Preprocessing'), ('differential', 'Differential Methylation'), ('region_analysis', 'Region Analysis'), ('correlation', 'Correlation'), ('enrichment', 'Enrichment')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='hormone_app.analysisjob')),
            ],
            options={
                'unique_together': {('job', 'group', 'name')},
            },
        ),
    ]
