# Generated by Django 4.2 on 2025-11-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hormone_app', '0006_analysisjob_geneanalysistask_uploadedfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hormonerelatedgene',
            name='related_genes',
        ),
        migrations.AddField(
            model_name='hormonerelatedgene',
            name='related_diseases',
            field=models.TextField(blank=True, null=True, verbose_name='相关疾病'),
        ),
        migrations.AddField(
            model_name='hormonerelatedgene',
            name='related_geneid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='相关基因ID'),
        ),
        migrations.AlterField(
            model_name='hormonerelatedgene',
            name='gene_sequence',
            field=models.TextField(blank=True, null=True, verbose_name='基因序列'),
        ),
        migrations.AlterField(
            model_name='hormonerelatedgene',
            name='hormone_name',
            field=models.CharField(max_length=255, verbose_name='激素名称'),
        ),
        migrations.AlterField(
            model_name='hormonerelatedgene',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hormonerelatedgene',
            name='pmid',
            field=models.IntegerField(blank=True, null=True, verbose_name='PubMed ID'),
        ),
    ]
