# Generated by Django 4.2 on 2025-11-27 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hormone_app', '0007_remove_hormonerelatedgene_related_genes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hormonerelatedgene',
            old_name='related_geneid',
            new_name='related_genes',
        ),
    ]
