# Generated by Django 4.2 on 2026-02-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hormone_app', '0008_rename_related_geneid_hormonerelatedgene_related_genes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hormonereceptorfull',
            options={'verbose_name': '肽类激素受体信息', 'verbose_name_plural': '肽类激素受体信息'},
        ),
        migrations.AlterModelOptions(
            name='hormonereceptorinfo',
            options={'verbose_name': '非肽类激素受体信息', 'verbose_name_plural': '非肽类激素受体信息'},
        ),
        migrations.AddField(
            model_name='hormonerelatedgene',
            name='DO_ID',
            field=models.CharField(max_length=50, null=True, verbose_name='DO编号'),
        ),
        migrations.AddField(
            model_name='hormonerelatedgene',
            name='DO_Match_disease_names',
            field=models.CharField(max_length=255, null=True, verbose_name='DO匹配疾病名称'),
        ),
        migrations.AddField(
            model_name='hormonerelatedgene',
            name='DO_Standardized_Terminology',
            field=models.TextField(null=True, verbose_name='DO标准化术语'),
        ),
        migrations.AlterField(
            model_name='hormonereceptorfull',
            name='hormone_coding_genes',
            field=models.TextField(blank=True, db_column='hormone coding genes', null=True),
        ),
        migrations.AlterField(
            model_name='hormonereceptorfull',
            name='hormone_coding_genes_sequence',
            field=models.TextField(blank=True, db_column='hormone coding genes sequence', null=True),
        ),
        migrations.AlterField(
            model_name='hormonereceptorfull',
            name='hormone_name',
            field=models.TextField(blank=True, db_column='hormone name', null=True),
        ),
        migrations.AlterField(
            model_name='hormonereceptorfull',
            name='hormone_species_name',
            field=models.TextField(blank=True, db_column='hormone species name', null=True),
        ),
        migrations.AlterField(
            model_name='hormonereceptorfull',
            name='hormone_uniprot_id',
            field=models.TextField(blank=True, db_column='hormone uniProt ID', null=True),
        ),
        migrations.AlterField(
            model_name='hormonereceptorfull',
            name='id',
            field=models.CharField(max_length=100, db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hormonereceptorfull',
            name='receptor_coding_genes',
            field=models.TextField(blank=True, db_column='receptor coding genes', null=True),
        ),
        migrations.AlterField(
            model_name='hormonereceptorfull',
            name='receptor_coding_genes_sequence',
            field=models.TextField(blank=True, db_column='receptor coding genes sequence', null=True),
        ),
        migrations.AlterField(
            model_name='hormonereceptorfull',
            name='receptor_name',
            field=models.TextField(blank=True, db_column='receptor name', null=True),
        ),
        migrations.AlterField(
            model_name='hormonereceptorfull',
            name='receptor_species_name',
            field=models.TextField(blank=True, db_column='receptor species name', null=True),
        ),
        migrations.AlterField(
            model_name='hormonereceptorfull',
            name='receptor_uniprot_id',
            field=models.TextField(blank=True, db_column='receptor uniProt ID', null=True),
        ),
        migrations.AlterField(
            model_name='hormonereceptorinfo',
            name='hormone_name',
            field=models.TextField(blank=True, db_column='hormone name', null=True),
        ),
        migrations.AlterField(
            model_name='hormonereceptorinfo',
            name='id',
            field=models.TextField(blank=True, db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hormonereceptorinfo',
            name='pubchem_id',
            field=models.TextField(blank=True, db_column='Pubchem ID', null=True),
        ),
        migrations.AlterField(
            model_name='hormonereceptorinfo',
            name='receptor_coding_genes',
            field=models.TextField(blank=True, db_column='receptor coding genes', null=True),
        ),
        migrations.AlterField(
            model_name='hormonereceptorinfo',
            name='receptor_coding_genes_sequence',
            field=models.TextField(blank=True, db_column='receptor coding genes sequence', null=True),
        ),
        migrations.AlterField(
            model_name='hormonereceptorinfo',
            name='receptor_name',
            field=models.TextField(blank=True, db_column='receptor name', null=True),
        ),
        migrations.AlterField(
            model_name='hormonereceptorinfo',
            name='receptor_species_name',
            field=models.TextField(blank=True, db_column='receptor species name', null=True),
        ),
        migrations.AlterField(
            model_name='hormonereceptorinfo',
            name='receptor_uniprot_id',
            field=models.TextField(blank=True, db_column='receptor uniProt ID', null=True),
        ),
        migrations.AlterField(
            model_name='hormonerelatedgene',
            name='gene_sequence',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hormonerelatedgene',
            name='hormone_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hormonerelatedgene',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hormonerelatedgene',
            name='pmid',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hormonerelatedgene',
            name='related_diseases',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hormonerelatedgene',
            name='related_genes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='hormonereceptorfull',
            table='hormone_tailei',
        ),
        migrations.AlterModelTable(
            name='hormonereceptorinfo',
            table='hormone_feitailei',
        ),
        migrations.AlterModelTable(
            name='hormonerelatedgene',
            table='hormone_data',
        ),
    ]
