# Generated by Django 4.2 on 2026-02-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hormone_app', '0009_alter_hormonereceptorfull_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hormonereceptorfull',
            name='id',
            field=models.TextField(db_column='ID', primary_key=True, serialize=False),
        ),
    ]
