# Generated by Django 4.2 on 2026-02-09 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hormone_app', '0010_alter_hormonereceptorfull_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastTask',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=20)),
                ('sequence_type', models.CharField(max_length=20)),
                ('sequence_file', models.CharField(blank=True, max_length=500, null=True)),
                ('database_requested', models.CharField(blank=True, max_length=50, null=True)),
                ('database_actual', models.CharField(blank=True, max_length=50, null=True)),
                ('program', models.CharField(blank=True, max_length=20, null=True)),
                ('evalue', models.CharField(blank=True, max_length=20, null=True)),
                ('max_hits', models.CharField(blank=True, max_length=20, null=True)),
                ('result_file', models.CharField(blank=True, max_length=500, null=True)),
                ('csv_result_file', models.CharField(blank=True, max_length=500, null=True)),
                ('fasta_hits_file', models.CharField(blank=True, max_length=500, null=True)),
                ('xml_report_file', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
