# Generated by Django 4.2 on 2026-02-09 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hormone_app', '0011_blasttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hormonereceptorfull',
            name='id',
            field=models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False),
        ),
    ]
