# Generated by Django 4.2 on 2026-02-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hormone_app', '0012_alter_hormonereceptorfull_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blasttask',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='blasttask',
            name='database_actual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='blasttask',
            name='database_requested',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
