# Generated by Django 4.2 on 2026-02-09 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hormone_app', '0013_blasttask_error_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNAMethylationTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='created', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('files', models.JSONField(blank=True, default=list)),
                ('results', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'dna_methylation_tasks',
            },
        ),
    ]
