# Generated by Django 4.2 on 2026-02-09 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hormone_app', '0014_dnamethylationtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptomeAnalysisTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(default='anonymous', max_length=100)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('files', models.JSONField(blank=True, default=dict)),
                ('analysis_type', models.CharField(default='transcriptome', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('current_step', models.CharField(default='Initializing', max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transcriptome_analysis_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptomeAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('differential_expression', models.JSONField(blank=True, default=dict)),
                ('enrichment', models.JSONField(blank=True, default=dict)),
                ('file_paths', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_relation', to='hormone_app.transcriptomeanalysistask')),
            ],
            options={
                'db_table': 'transcriptome_analysis_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptomeAnalysisFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('file_type', models.CharField(choices=[('fastq-files', 'FASTQ文件'), ('sample-metadata', '样本元数据'), ('reference-genome', '参考基因组'), ('gene-list', '基因列表'), ('custom-genesets', '自定义基因集')], max_length=50)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_relation', to='hormone_app.transcriptomeanalysistask')),
            ],
            options={
                'db_table': 'transcriptome_analysis_files',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transcriptomeanalysistask',
            index=models.Index(fields=['user', 'status'], name='transcripto_user_id_caeb1d_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptomeanalysistask',
            index=models.Index(fields=['created_at'], name='transcripto_created_7a3765_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptomeanalysisfile',
            index=models.Index(fields=['task', 'file_type'], name='transcripto_task_id_ae4e32_idx'),
        ),
    ]
