# Generated by Django 4.2 on 2026-02-10 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hormone_app', '0015_transcriptomeanalysistask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeggAnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client_id', models.CharField(max_length=255)),
                ('client_ip', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('created', '已创建'), ('uploaded', '已上传文件'), ('running', '分析中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='created', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('genes', models.JSONField(blank=True, default=list)),
                ('gene_count', models.IntegerField(default=0)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='kegg_results/')),
                ('results', models.JSONField(blank=True, default=dict)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
