# Generated by Django 4.2 on 2026-02-11 08:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hormone_app', '0016_kegganalysistask'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeggGene',
            fields=[
                ('gene_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='KEGG基因ID')),
                ('symbol', models.CharField(db_index=True, max_length=50, verbose_name='基因符号')),
                ('name', models.CharField(max_length=500, verbose_name='基因名称')),
                ('entrez_id', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Entrez ID')),
                ('uniprot_id', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='UniProt ID')),
                ('ensembl_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Ensembl ID')),
                ('chromosome', models.CharField(blank=True, max_length=20, verbose_name='染色体')),
                ('start_position', models.BigIntegerField(blank=True, null=True, verbose_name='起始位置')),
                ('end_position', models.BigIntegerField(blank=True, null=True, verbose_name='终止位置')),
                ('strand', models.CharField(blank=True, max_length=1, verbose_name='链方向')),
                ('function', models.TextField(blank=True, verbose_name='功能描述')),
                ('pathway_count', models.IntegerField(default=0, verbose_name='通路数量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KEGG基因',
                'verbose_name_plural': 'KEGG基因',
            },
        ),
        migrations.CreateModel(
            name='KeggGenePathway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(default='member', max_length=50, verbose_name='关联类型')),
                ('evidence', models.CharField(blank=True, max_length=100, verbose_name='证据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '基因-通路关联',
                'verbose_name_plural': '基因-通路关联',
            },
        ),
        migrations.CreateModel(
            name='KeggOrganism',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='KEGG代码')),
                ('name', models.CharField(max_length=200, verbose_name='生物体名称')),
                ('scientific_name', models.CharField(blank=True, max_length=200, verbose_name='学名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('taxonomy', models.TextField(blank=True, verbose_name='分类信息')),
            ],
            options={
                'verbose_name': 'KEGG生物体',
                'verbose_name_plural': 'KEGG生物体',
            },
        ),
        migrations.CreateModel(
            name='KeggPathway',
            fields=[
                ('pathway_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='通路ID')),
                ('name', models.CharField(max_length=500, verbose_name='通路名称')),
                ('description', models.TextField(blank=True, verbose_name='通路描述')),
                ('category', models.CharField(choices=[('metabolism', '代谢'), ('genetic', '遗传信息处理'), ('environmental', '环境信息处理'), ('cellular', '细胞过程'), ('organismal', '生物体系统'), ('human', '人类疾病'), ('drug', '药物开发')], max_length=50, verbose_name='分类')),
                ('subcategory', models.CharField(blank=True, max_length=100, verbose_name='子分类')),
                ('gene_count', models.IntegerField(default=0, verbose_name='基因数量')),
                ('compound_count', models.IntegerField(default=0, verbose_name='化合物数量')),
                ('reaction_count', models.IntegerField(default=0, verbose_name='反应数量')),
                ('kegg_url', models.URLField(blank=True, verbose_name='KEGG链接')),
                ('image_url', models.URLField(blank=True, verbose_name='通路图链接')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KEGG通路',
                'verbose_name_plural': 'KEGG通路',
            },
        ),
        migrations.CreateModel(
            name='KeggPathwayHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='层级')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='hormone_app.keggpathway', verbose_name='子通路')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hormone_app.keggpathway', verbose_name='父通路')),
            ],
            options={
                'verbose_name': '通路层级',
                'verbose_name_plural': '通路层级',
            },
        ),
        migrations.AddIndex(
            model_name='keggpathway',
            index=models.Index(fields=['category'], name='hormone_app_categor_adca7d_idx'),
        ),
        migrations.AddIndex(
            model_name='keggpathway',
            index=models.Index(fields=['pathway_id'], name='hormone_app_pathway_0ed204_idx'),
        ),
        migrations.AddField(
            model_name='kegggenepathway',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_relations', to='hormone_app.kegggene', verbose_name='基因'),
        ),
        migrations.AddField(
            model_name='kegggenepathway',
            name='pathway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_relations', to='hormone_app.keggpathway', verbose_name='通路'),
        ),
        migrations.AddField(
            model_name='kegggene',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genes', to='hormone_app.keggorganism', verbose_name='生物体'),
        ),
        migrations.AlterUniqueTogether(
            name='keggpathwayhierarchy',
            unique_together={('parent', 'child')},
        ),
        migrations.AddIndex(
            model_name='kegggenepathway',
            index=models.Index(fields=['gene', 'pathway'], name='hormone_app_gene_id_59b11c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kegggenepathway',
            unique_together={('gene', 'pathway')},
        ),
        migrations.AddIndex(
            model_name='kegggene',
            index=models.Index(fields=['symbol'], name='hormone_app_symbol_1d9271_idx'),
        ),
        migrations.AddIndex(
            model_name='kegggene',
            index=models.Index(fields=['organism'], name='hormone_app_organis_85da8a_idx'),
        ),
        migrations.AddIndex(
            model_name='kegggene',
            index=models.Index(fields=['entrez_id'], name='hormone_app_entrez__4daa30_idx'),
        ),
    ]
