# Generated by Django 4.2 on 2026-02-11 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hormone_app', '0017_kegggene_kegggenepathway_keggorganism_keggpathway_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegggene',
            name='chromosome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='染色体'),
        ),
        migrations.AlterField(
            model_name='kegggene',
            name='ensembl_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Ensembl ID'),
        ),
        migrations.AlterField(
            model_name='kegggene',
            name='entrez_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Entrez ID'),
        ),
        migrations.AlterField(
            model_name='kegggene',
            name='function',
            field=models.TextField(blank=True, null=True, verbose_name='功能描述'),
        ),
        migrations.AlterField(
            model_name='kegggene',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='基因名称'),
        ),
        migrations.AlterField(
            model_name='kegggene',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genes', to='hormone_app.keggorganism', verbose_name='生物体'),
        ),
        migrations.AlterField(
            model_name='kegggene',
            name='strand',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='链方向'),
        ),
        migrations.AlterField(
            model_name='kegggene',
            name='symbol',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='基因符号'),
        ),
        migrations.AlterField(
            model_name='kegggene',
            name='uniprot_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='UniProt ID'),
        ),
        migrations.AlterField(
            model_name='kegggenepathway',
            name='evidence',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='证据'),
        ),
        migrations.AlterField(
            model_name='kegggenepathway',
            name='relation_type',
            field=models.CharField(blank=True, default='member', max_length=50, null=True, verbose_name='关联类型'),
        ),
        migrations.AlterField(
            model_name='keggorganism',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='keggorganism',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='学名'),
        ),
        migrations.AlterField(
            model_name='keggorganism',
            name='taxonomy',
            field=models.TextField(blank=True, null=True, verbose_name='分类信息'),
        ),
        migrations.AlterField(
            model_name='keggpathway',
            name='category',
            field=models.CharField(blank=True, choices=[('metabolism', '代谢'), ('genetic', '遗传信息处理'), ('environmental', '环境信息处理'), ('cellular', '细胞过程'), ('organismal', '生物体系统'), ('human', '人类疾病'), ('drug', '药物开发')], max_length=50, null=True, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='keggpathway',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='通路描述'),
        ),
        migrations.AlterField(
            model_name='keggpathway',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='通路图链接'),
        ),
        migrations.AlterField(
            model_name='keggpathway',
            name='kegg_url',
            field=models.URLField(blank=True, null=True, verbose_name='KEGG链接'),
        ),
        migrations.AlterField(
            model_name='keggpathway',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='子分类'),
        ),
        migrations.AlterField(
            model_name='keggpathwayhierarchy',
            name='level',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='层级'),
        ),
        migrations.AddIndex(
            model_name='kegggene',
            index=models.Index(fields=['organism', 'symbol'], name='hormone_app_organis_bcd8af_idx'),
        ),
        migrations.AddIndex(
            model_name='kegggenepathway',
            index=models.Index(fields=['relation_type'], name='hormone_app_relatio_4b22ec_idx'),
        ),
        migrations.AddIndex(
            model_name='keggorganism',
            index=models.Index(fields=['code'], name='hormone_app_code_1cb446_idx'),
        ),
        migrations.AddIndex(
            model_name='keggpathway',
            index=models.Index(fields=['name'], name='hormone_app_name_e672c0_idx'),
        ),
        migrations.AddIndex(
            model_name='keggpathwayhierarchy',
            index=models.Index(fields=['parent', 'level'], name='hormone_app_parent__8daa7a_idx'),
        ),
        migrations.AddIndex(
            model_name='keggpathwayhierarchy',
            index=models.Index(fields=['child', 'level'], name='hormone_app_child_i_11a7e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='kegggene',
            constraint=models.UniqueConstraint(condition=models.Q(('symbol__isnull', False)), fields=('organism', 'symbol'), name='unique_organism_gene_symbol'),
        ),
    ]
