# Generated by Django 4.2 on 2026-02-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hormone_app', '0018_alter_kegggene_chromosome_alter_kegggene_ensembl_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='kegggene',
            name='unique_organism_gene_symbol',
        ),
    ]
