# Generated by Django 4.2 on 2026-03-03 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hormone_app', '0019_remove_kegggene_unique_organism_gene_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhylogeneticTree',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hormone_family', models.CharField(db_index=True, max_length=100, verbose_name='激素家族')),
                ('tree_newick', models.TextField(verbose_name='Newick格式树')),
                ('species_count', models.IntegerField(verbose_name='物种数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统发育树',
                'verbose_name_plural': '系统发育树',
                'db_table': 'phylogenetic_trees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SequenceConservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=100, verbose_name='物种')),
                ('similarity_score', models.FloatField(verbose_name='相似度分数')),
                ('alignment_length', models.IntegerField(verbose_name='比对长度')),
                ('hormone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conservation', to='hormone_app.hormonereceptorfull', verbose_name='激素')),
            ],
            options={
                'verbose_name': '序列保守性',
                'verbose_name_plural': '序列保守性',
                'db_table': 'sequence_conservation',
                'unique_together': {('hormone', 'species')},
            },
        ),
        migrations.CreateModel(
            name='GNPrediction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prediction_score', models.FloatField(help_text='Prediction score (0-1)', verbose_name='预测分数')),
                ('confidence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, verbose_name='置信度')),
                ('model_version', models.CharField(max_length=50, verbose_name='模型版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('hormone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gnn_predictions', to='hormone_app.hormonereceptorfull', verbose_name='激素')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gnn_receptor_predictions', to='hormone_app.hormonereceptorfull', verbose_name='受体')),
            ],
            options={
                'verbose_name': 'GNN预测',
                'verbose_name_plural': 'GNN预测',
                'db_table': 'gn_predictions',
                'ordering': ['-prediction_score'],
                'unique_together': {('hormone', 'receptor')},
            },
        ),
    ]
