# Generated by Django 4.2 on 2026-03-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hormone_app', '0020_phylogenetictree_sequenceconservation_gnprediction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gnprediction',
            options={'verbose_name': 'GNN预测', 'verbose_name_plural': 'GNN预测'},
        ),
        migrations.AlterUniqueTogether(
            name='gnprediction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gnprediction',
            name='hormone_non_peptide_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='非肽类激素ID'),
        ),
        migrations.AddField(
            model_name='gnprediction',
            name='hormone_peptide_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='肽类激素ID'),
        ),
        migrations.AddField(
            model_name='gnprediction',
            name='hormone_type',
            field=models.CharField(blank=True, choices=[('peptide', '肽类激素'), ('non_peptide', '非肽类激素')], max_length=20, null=True, verbose_name='激素类型'),
        ),
        migrations.AddField(
            model_name='gnprediction',
            name='receptor_non_peptide_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='非肽类受体ID'),
        ),
        migrations.AddField(
            model_name='gnprediction',
            name='receptor_peptide_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='肽类受体ID'),
        ),
        migrations.AddField(
            model_name='gnprediction',
            name='receptor_type',
            field=models.CharField(blank=True, choices=[('peptide', '肽类激素'), ('non_peptide', '非肽类激素')], max_length=20, null=True, verbose_name='受体类型'),
        ),
        migrations.AlterField(
            model_name='gnprediction',
            name='confidence_level',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=10, verbose_name='置信度'),
        ),
        migrations.AlterField(
            model_name='gnprediction',
            name='model_version',
            field=models.CharField(default='gnn_v1.0', max_length=50, verbose_name='模型版本'),
        ),
        migrations.AddIndex(
            model_name='gnprediction',
            index=models.Index(fields=['prediction_score'], name='gn_predicti_predict_c9f048_idx'),
        ),
        migrations.AddIndex(
            model_name='gnprediction',
            index=models.Index(fields=['confidence_level'], name='gn_predicti_confide_5dfce6_idx'),
        ),
        migrations.AddIndex(
            model_name='gnprediction',
            index=models.Index(fields=['hormone_peptide_id'], name='gn_predicti_hormone_28802a_idx'),
        ),
        migrations.AddIndex(
            model_name='gnprediction',
            index=models.Index(fields=['hormone_non_peptide_id'], name='gn_predicti_hormone_f17d85_idx'),
        ),
        migrations.AddIndex(
            model_name='gnprediction',
            index=models.Index(fields=['receptor_peptide_id'], name='gn_predicti_recepto_2dc8ab_idx'),
        ),
        migrations.AddIndex(
            model_name='gnprediction',
            index=models.Index(fields=['receptor_non_peptide_id'], name='gn_predicti_recepto_f5c293_idx'),
        ),
        migrations.RemoveField(
            model_name='gnprediction',
            name='hormone',
        ),
        migrations.RemoveField(
            model_name='gnprediction',
            name='receptor',
        ),
    ]
