"""
Django settings for animal_hormone project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.apps import AppConfig
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv(os.path.join(Path(__file__).resolve().parent.parent, '.env'))


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DASHSCOPE_API_KEY = os.environ.get('DASHSCOPE_API_KEY', '')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'fallback-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['39.99.45.167','43.99.62.219','127.0.0.1','localhost','panhorm.cn','www.panhorm.cn']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hormone_app'
]

CSRF_TRUSTED_ORIGINS = [
    'http://39.99.45.167',
    'https://43.99.62.219',
    'http://43.99.62.219',
    # 若用 https 访问，再加 'https://39.99.45.167'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'animal_hormone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'hormone_app/templates'),
                 
                 ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'animal_hormone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 使用MySQL数据库
        'NAME': os.environ.get('DB_NAME', 'animal_hormone'),       # 数据库名称
        'USER': os.environ.get('DB_USER', 'hhh'),     # 数据库用户名
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),  # 数据库密码
        'HOST': '127.0.0.1',       # 数据库地址
        'PORT': '3306',            # 数据库端口
        'OPTIONS': {
            'charset': 'utf8mb4',  # 支持中文和表情符号
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static_coll')  # 收集静态文件的目录
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # 项目里存放静态文件的目录，与 STATIC_ROOT 不同
]


# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 扩大请求体和文件上传限制（根据需求调整，如100MB）
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
# ==============================
# 安全日志配置 - 仅记录到项目 logs 目录
# ==============================
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "django_file": {
            "level": "ERROR", # 你可以保持 ERROR，或者改为 INFO
            "class": "logging.FileHandler",
            "filename": str(LOGS_DIR / "django_error.log"),
            "formatter": "verbose",
        },
        "app_file": {
            "level": "INFO", # <--- 将这里从 "ERROR" 改为 "INFO"
            "class": "logging.FileHandler",
            "filename": str(LOGS_DIR / "app_error.log"), # <--- 文件名也可以改得更通用一点，如 hormone_app.log
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["django_file"],
            "level": "ERROR", # 你可以保持 ERROR，或者改为 INFO
            "propagate": True,
        },
        "hormone_app": {
            "handlers": ["app_file"], # <--- 确保 handler 指向你刚修改的 app_file
            "level": "INFO", # <--- 将这里从 "ERROR" 改为 "INFO"
            "propagate": True,
        },
    },
}
# ==============================
# HTTPS 安全配置
# ==============================

# SSL/HTTPS（nginx已处理重定向，Django只需识别代理头）
SECURE_SSL_REDIRECT = False
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# 安全Cookie（仅HTTPS传输）
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# 防止JavaScript访问Session Cookie
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False

# HSTS（强制浏览器使用HTTPS，有效期1年）
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# 浏览器安全头
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Session过期时间（7天）
SESSION_COOKIE_AGE = 7 * 24 * 60 * 60
